### ISSUE TITLE
JOSS review: fbs.plot_years() from README does not work

### ISSUE THREAD

**Issue by kanishkan91** [FixOurFood/AgriFoodPy#67]
Not sure what is going on but I got this error (attached below). If this is because I'm missing some packages, those should be added to the dependencies. 

![image](https://github.com/FixOurFood/AgriFoodPy/assets/37234086/be9dad50-dc98-474b-80dc-9d39f404042b)

https://github.com/openjournals/joss-reviews/issues/6305

**Comment by jucordero** [comment]
Hi @kanishkan91 
Thank you very much for your time on reviewing AgriFoodPy.

I've looked into this and there seems to be an [issue](https://github.com/matplotlib/matplotlib/issues/26463) with PyCharm rather than a missing AgriFoodPy dependency.
According to this issue, the problem should be resolved by updating PyCharm to a more recent version (You are running 2021.3.3 which is somewhat old)
